(* ::Package:: *)

(* ::Input:: *)
(*MonteCarloPi[n_Integer]:=Module[{count,points,insidePoints,result},*)
(*count=0;*)
(*points=RandomReal[{-1,1},{n,2}];*)
(*insidePoints=Select[points,Norm[#]<=1&];*)
(*count=Length[insidePoints];*)
(**)
(*result=N[4 count/n];*)
(**)
(*{*)
(*Print[*)
(*Show[*)
(*ListPlot[*)
(*Tooltip[insidePoints,"To\[CHacek]ke v krogu"],*)
(*PlotStyle->Blue,AspectRatio->1,PlotLegends->{"To\[CHacek]ke v krogu"}],*)
(*ListPlot[*)
(*Tooltip[Complement[points,insidePoints],"To\[CHacek]ke zunaj kroga"],*)
(*PlotStyle->Red,PlotLegends->{"To\[CHacek]ke zunaj kroga"}]]],result}]*)
(**)
(**)
(**)
